# Generated by Django 3.0.6 on 2020-07-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='neighborhood',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
