# Generated by Django 3.0.6 on 2020-07-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_shippingaddress_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='', max_length=9),
            preserve_default=False,
        ),
    ]
