# Generated by Django 3.0.6 on 2020-07-04 16:40

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='landline_phone',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('MAS', 'Masculino'), ('FEM', 'Feminino')], max_length=9),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, validators=[store.validators.CustomUnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
