# Generated by Django 3.0.6 on 2020-07-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_ordered_complete',
            field=models.DateTimeField(null=True),
        ),
    ]
