# Generated by Django 3.0.6 on 2020-07-15 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_date_ordered_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_ordered_complete',
            new_name='date_order_completed',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_ordered',
            new_name='date_order_created',
        ),
    ]
