# Generated by Django 3.0.6 on 2020-07-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200714_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='rg',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
