# Generated by Django 3.0.6 on 2020-07-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200715_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
