# Generated by Django 3.0.6 on 2020-07-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200721_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutritional_infos_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
