# Generated by Django 3.0.6 on 2020-07-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20200721_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='rg',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
