# Generated by Django 3.0.6 on 2020-07-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20200722_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='uf',
        ),
        migrations.AddField(
            model_name='order',
            name='_shipping_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('waiting', 'Aguardando confirmação'), ('preparing', 'Preparando pedido'), ('shipping', 'Em trânsito'), ('delivered', 'Entregue')], default='waiting', max_length=9),
        ),
    ]
