# Generated by Django 3.0.6 on 2020-07-31 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20200730_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_service',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='Brasil', max_length=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('credit_card', 'Cartão de crédito'), ('paypal', 'PayPal'), ('bank_slip', 'Boleto bancário')], default=None, max_length=200),
        ),
    ]
