# Generated by Django 3.0.6 on 2020-08-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20200731_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='installments',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_service',
            field=models.CharField(choices=[('sedex', 'SEDEX'), ('pac', 'PAC')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('credit_card', 'Cartão de crédito'), ('paypal', 'PayPal'), ('bank_slip', 'Boleto bancário')], default=None, max_length=11),
        ),
    ]
