# Generated by Django 3.0.6 on 2020-08-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20200731_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('expiring_date', models.DateField()),
                ('holder_name', models.CharField(max_length=200)),
                ('security_code', models.IntegerField()),
                ('holder_is_customer', models.BooleanField()),
                ('holder_address_is_shipping', models.BooleanField()),
            ],
        ),
    ]
