# Generated by Django 3.0.6 on 2020-08-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_creditcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditCard',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='installments',
            new_name='number_of_installments',
        ),
        migrations.AddField(
            model_name='payment',
            name='value_of_installment',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
    ]
