# Generated by Django 3.0.6 on 2020-08-05 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20200803_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Aguardando confirmação'), ('preparing', 'Preparando pedido'), ('shipping', 'Em trânsito'), ('delivered', 'Entregue')], default='waiting', max_length=9)),
                ('service', models.CharField(choices=[('sedex', 'SEDEX'), ('pac', 'PAC')], max_length=5, null=True)),
                ('days_to_deliver', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='_shipping_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_status',
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.ShippingService'),
        ),
    ]
