# Generated by Django 3.0.6 on 2020-08-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20200804_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_order_completed',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_order_created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='order',
            name='requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='requested_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='shippingservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingservice',
            name='service',
            field=models.CharField(choices=[('04014', 'SEDEX'), ('04510', 'PAC')], max_length=5, null=True),
        ),
    ]
