# Generated by Django 3.0.6 on 2020-08-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20200806_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingservice',
            old_name='service',
            new_name='service_code',
        ),
        migrations.AddField(
            model_name='shippingservice',
            name='_tracking_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
