# Generated by Django 3.0.6 on 2020-08-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20200806_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingservice',
            name='status',
            field=models.CharField(choices=[('requested', 'Aguardando confirmação'), ('payed', 'Pagamento realizado'), ('preparing', 'Preparando pedido'), ('shipped', 'Entregue')], max_length=9, null=True),
        ),
    ]
