# Generated by Django 3.0.6 on 2020-08-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20200812_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingservice',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('requested', 'Aguardando confirmação'), ('payed', 'Pagamento realizado'), ('preparing', 'Preparando pedido'), ('shipped', 'Entregue')], default='requested', max_length=9),
        ),
    ]
