# Generated by Django 3.0.6 on 2020-08-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20200812_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('requested', 'Aguardando pagamento'), ('payed', 'Pagamento confirmado'), ('preparing', 'Preparando pedido'), ('shipped', 'Pedido enviado')], default='requested', max_length=9),
        ),
    ]
