# Generated by Django 3.0.6 on 2020-08-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20200817_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('requested', 'Aguardando pagamento'), ('payed', 'Pagamento confirmado'), ('preparing', 'Preparando pedido'), ('shipped', 'Pedido enviado')], default='analysing', max_length=9),
        ),
    ]
