# Generated by Django 3.0.6 on 2020-08-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20200817_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('analysing', 'Em análise'), ('requested', 'Aguardando pagamento'), ('payed', 'Pagamento confirmado'), ('preparing', 'Preparando pedido'), ('shipped', 'Pedido enviado')], default='analysing', max_length=9),
        ),
    ]
