# Generated by Django 3.0.6 on 2020-08-19 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_auto_20200818_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='landline_phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='rg',
        ),
    ]
