from decimal import Decimal
import json
from uuid import uuid4

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.http import JsonResponse
from django.utils.http import urlsafe_base64_decode

from .choices import PAC, SEDEX
from .forms import (
    CustomAuthenticationForm,
    CustomerCreationForm,
    CustomPasswordResetForm,
    CustomSetPasswordForm,
    CustomUserChangeForm,
    CustomUserCreationForm,
    organize_installment_text,
    ShippingAddressForm,
    ShippingAddressChangeForm,
)
from .helpers import exclude_mask_chars, get_installment_options
from .models import CustomUser, Order, OrderItem, Product, ShippingAddress
from .utils import (
    get_context,
    _get_shipping_infos,
    render_authenticated_checkout,
    render_checkout,
)


def store(request):
    """Funcao responsavel pela view da pagina principal"""
    context = get_context(request)
    delete_cokie = context.pop("delete_cookie", False)
    cookie = context.pop("set_cookie", False)

    response = render(
        request,
        "store/store.html",
        {**context, "products": Product.objects.all()},
    )

    if delete_cokie:
        response.delete_cookie("device")

    if cookie:  # device id was generated by the backend
        # by some reason the front end don't generate the cookie
        # only in this view
        response.set_cookie("device", cookie)
    return response


def cart(request):
    return render(request, "store/cart.html", get_context(request))


def checkout(request):
    """Funcao responsavel pelo checkout de um pedido"""
    if request.user.is_authenticated:
        return render_authenticated_checkout(request)
    return render_checkout(request)


def update_item(request):
    """Funcao para atualizar um item do carrinho"""
    data = json.loads(request.body)
    product = Product.objects.get(id=data["productId"])

    order = get_context(request)["order"]
    order_item, _ = OrderItem.objects.get_or_create(order=order, product=product)

    if data["action"] == "add":
        order_item.quantity += data["quantity"]
    if data["action"] == "subtract":
        order_item.quantity -= data["quantity"]

    order_item.save()

    if order_item.quantity <= 0:
        order_item.delete()

    return JsonResponse("Item was updated", safe=False)


def remove_item(request):
    data = json.loads(request.body)
    product = Product.objects.get(id=data["productId"])
    order = get_context(request)["order"]
    order_item = OrderItem.objects.get(order=order, product=product)
    order_item.delete()

    return JsonResponse("Item was removed", safe=False)


def remove_address(request):
    data = json.loads(request.body)
    address = ShippingAddress.objects.get(id=data["addressId"])
    address.delete()

    return JsonResponse("Address was removed", safe=False)


def register(request):
    """Funcao responsavel pela view de registro de cliente"""
    if request.user.is_authenticated:
        return redirect("store")

    user_form = CustomUserCreationForm(prefix="user_form", page="register")
    customer_form = CustomerCreationForm(prefix="customer_form", page="register")

    if request.method == "POST":
        user_form = CustomUserCreationForm(
            request.POST, prefix="user_form", page="register"
        )
        customer_form = CustomerCreationForm(
            request.POST, prefix="customer_form", page="register"
        )
        if user_form.is_valid() and customer_form.is_valid():
            user = user_form.save()
            # user.is_active = False; user must activate?
            customer_form.save(user=user, device=request.COOKIES.get("device", uuid4()))
            # TODO: Send email to customer
            login(request, user)
            response = redirect("store")
            response.delete_cookie("device")
            return response

    return render(
        request,
        "store/register.html",
        {
            **get_context(request),
            "user_form": user_form,
            "customer_form": customer_form,
        },
    )


def register_address_from_checkout(request):
    """View responsavel por registrar um endereço da pagina de checkout"""
    data = json.loads(request.body)

    if ShippingAddress.objects.filter(customer=request.user.customer):
        main = False
    else:
        main = True

    ShippingAddress.objects.create(
        customer=request.user.customer,
        zip_code=exclude_mask_chars(data["shippingFormData"]["zip_code"]),
        address=data["shippingFormData"]["address"],
        number=data["shippingFormData"]["number"],
        neighborhood=data["shippingFormData"]["neighborhood"],
        complement=data["shippingFormData"]["complement"],
        reference=data["shippingFormData"]["reference"],
        city=data["shippingFormData"]["city"],
        uf=data["shippingFormData"]["uf"],
        country=data["shippingFormData"]["country"],
        main=main,
    )
    return JsonResponse("", safe=False)


def login_user(request):
    """Funcao responsavel pela view de login do cliente"""
    if request.user.is_authenticated:
        return redirect("store")
    authentication_form = CustomAuthenticationForm()
    if request.method == "POST":
        authentication_form = CustomAuthenticationForm(data=request.POST)
        if authentication_form.is_valid():
            user = authenticate(
                request,
                email=request.POST.get("username"),
                password=request.POST.get("password"),
            )
            login(request, user)
            return redirect("store")
        messages.error(request, "E-mail ou senha incorretos!")

    return render(
        request,
        "store/login.html",
        {**get_context(request), "authentication_form": authentication_form},
    )


def logout_user(request):
    logout(request)
    return redirect("store")


def forgot_password(request):
    """Funcao responsavel pela view de requisicao de nova senha do cliente"""
    if request.user.is_authenticated:
        return redirect("store")

    form = CustomPasswordResetForm()
    if request.method == "POST":
        form = CustomPasswordResetForm(request.POST)
        if form.is_valid() and CustomUser.objects.filter(email=request.POST["email"]):
            form.save(
                email_template_name="store/custom_password_reset_email.html",
                subject_template_name="store/custom_password_reset_subject.txt",
                from_email=settings.EMAIL_HOST_USER,
                request=request,
            )
            request.session["email"] = request.POST["email"]
            return redirect("password_reset_done")

        messages.warning(
            request,
            f'Parece que o e-mail "{request.POST["email"]}" não está cadastrado no sistema...',
        )
    return render(
        request, "store/forgot_password.html", {**get_context(request), "form": form}
    )


def password_reset_done(request):
    return render(
        request,
        "store/password_reset_done.html",
        {**get_context(request), "email": request.session["email"]},
    )


def password_reset_confirm(request, uidb64, token):  # pylint: disable=unused-argument
    """View responsável por redefinir a senha"""
    # TODO: Make this view expirable
    user = CustomUser.objects.get(pk=urlsafe_base64_decode(uidb64).decode())
    form = CustomSetPasswordForm(user=user)
    if request.method == "POST":
        form = CustomSetPasswordForm(user=user, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("password_reset_complete")

    return render(
        request,
        "store/password_reset_confirm.html",
        {**get_context(request), "form": form},
    )


def password_reset_complete(request):
    return render(request, "store/password_reset_complete.html", get_context(request))


def view_product(request, product_id):
    return render(
        request,
        "store/view_product.html",
        {
            **get_context(request),
            "product": Product.objects.get(pk=product_id),
        },
    )


@login_required(login_url="/login")
def order_success(request, transaction_id):
    """Funcao responsavel pela view de um pedido bem sucedido"""
    try:
        requested_order = Order.objects.get(
            customer=request.user.customer, transaction_id=transaction_id
        )
    except Order.DoesNotExist:
        return render(
            request,
            "store/order_success.html",
            {**get_context(request), "requested_order": None, "requested_items": None},
        )

    requested_items = requested_order.orderitem_set.all().order_by("id")
    return render(
        request,
        "store/order_success.html",
        {
            **get_context(request),
            "requested_order": requested_order,
            "requested_items": requested_items,
        },
    )


@login_required(login_url="/login")
def user_page(request):
    orders = (
        Order.objects.filter(customer=request.user.customer)
        .exclude(status="analysing")
        .order_by("-requested_at")
    )
    return render(
        request,
        "store/user_page.html",
        {**get_context(request), "orders": orders},
    )


@login_required(login_url="/login")
def view_order(request, order_id):
    """Funcao responsavel pela view de visualizacao de um pedido do cliente"""
    try:
        requested_order = Order.objects.get(customer=request.user.customer, id=order_id)
    except Order.DoesNotExist:
        return render(
            request,
            "store/view_order.html",
            {**get_context(request), "requested_order": None, "requested_items": None},
        )

    requested_items = requested_order.orderitem_set.all().order_by("id")
    return render(
        request,
        "store/view_order.html",
        {
            **get_context(request),
            "requested_order": requested_order,
            "requested_items": requested_items,
        },
    )


@login_required(login_url="/login")
def view_profile(request):
    """Funcao responsavel pela view de visualizacao dos dados do cliente"""
    form = CustomUserChangeForm(user=request.user)
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, user=request.user)
        if form.is_valid():
            if form.has_different_values:
                user = form.save()
                form = CustomUserChangeForm(user=user)
                messages.success(request, "Dados alterados com sucesso!")
            else:
                form = CustomUserChangeForm(user=request.user)
                messages.warning(
                    request, "Modifique algum dado para alterar sua conta!"
                )
    return render(
        request,
        "store/view_profile.html",
        {
            **get_context(request),
            "form": form,
            "addresses": ShippingAddress.objects.filter(customer=request.user.customer),
        },
    )


@login_required(login_url="/login")
def view_address(request, address_id):
    """Funcao responsavel pela view de visualizacao de um edenreco do cliente"""
    try:
        shipping_address = ShippingAddress.objects.get(
            customer=request.user.customer, pk=address_id
        )
    except ShippingAddress.DoesNotExist:
        return render(
            request,
            "store/view_address.html",
            {**get_context(request), "form": None, "address_id": None},
        )

    shipping_address = ShippingAddress.objects.get(pk=address_id)
    form = ShippingAddressChangeForm(shipping_address=shipping_address)
    if request.method == "POST":
        form = ShippingAddressChangeForm(
            request.POST, shipping_address=shipping_address
        )
        new_values = form.is_valid()
        if new_values:
            shipping_address = form.save(new_values, customer=request.user.customer)
            form = ShippingAddressChangeForm(shipping_address=shipping_address)
            messages.success(request, "Dados alterados com sucesso!")
        else:
            messages.warning(request, "Modifique algum dado para alterar o endereço!")

    return render(
        request,
        "store/view_address.html",
        {**get_context(request), "form": form, "address_id": address_id},
    )


@login_required(login_url="/login")
def view_all_addresses(request):
    return render(
        request,
        "store/view_all_addresses.html",
        {
            **get_context(request),
            "addresses": ShippingAddress.objects.filter(
                customer=request.user.customer
            ).order_by("-main"),
        },
    )


@login_required(login_url="/login")
def register_address(request):
    form = ShippingAddressForm(page="user")
    if request.method == "POST":
        form = ShippingAddressForm(request.POST, page="user")
        if form.is_valid():
            form.save(customer=request.user.customer)
            return redirect("view_all_addresses")
    return render(
        request,
        "store/register_address.html",
        {**get_context(request), "form": form},
    )


def get_shipping_infos(request):
    """Funcao responsavel por obter as opcoes de frete de um pedido"""
    zip_code = json.loads(request.body)["zip_code"]
    return JsonResponse(
        {
            "PAC": _get_shipping_infos(zip_code=zip_code, service_code=PAC),
            "SEDEX": _get_shipping_infos(zip_code=zip_code, service_code=SEDEX),
        }
    )


def load_credit_card_installments(request):
    total = Decimal(request.GET.get("total", "0").replace(",", "."))
    installments = organize_installment_text(get_installment_options(total=total))

    return render(
        request,
        "store/credit_card_dropdown_installments_options.html",
        {"installments": installments},
    )
